spring:
  main:
    banner-mode: off
    lazy-initialization: false
  devtools:
    livereload:
      enabled: false
    add-properties: false
logging:
  level:
    org.springframework: off
    root: off
